### ISSUE TITLE
Downloaded Project don't work

### ISSUE THREAD

**Issue by CuteBladeYT** [PullJosh/leopard#101]
So when I download converted project, when I open **index.html**, only `Green Flag` button shows, and nothing other than it, and the only way I can see it, is opening it on [CodeSandbox.io](https://codesandbox.io) or on [Leopard Converter](https://leopardjs.vercel.app).

**Comment by PullJosh** [comment]
If you open the console (which, depending on your web browser, you can probably get to by right clicking on the page, choosing "Inspect", and then going to the console tab), are there any errors or important messages?

**Comment by CuteBladeYT** [comment]
This is what I got
![image](https://user-images.githubusercontent.com/78739707/127038724-7ff3f517-7040-4616-8b1e-b73cc7e44139.png)

I think it's because files opened locally can't access internet sources, and these online sources is files `index.esm.js` and `index.min.css`

**Comment by PullJosh** [comment]
Close. The problem isn't loading files from the internet, through. It's that the way we're loading scripts, with the javascript `import` keyword, doesn't allow loading files from `file://`.

If you want to run things locally, you'll have to serve the files on `localhost`, which I'm sure you can find tutorials for on Google. (Maybe search for something like "serve static files on localhost"?)

**Comment by CuteBladeYT** [comment]
Alright, thanks for help!

**Comment by CuteBladeYT** [comment]
Well, I know free hosting site where I can host this project, but in future it can be useless because it allows me to upload only 1MB files and my project is getting bigger and bigger but I will search for other solutions

**Comment by CuteBladeYT** [comment]
I found a way using Github pages. Also thanks for help
