### ISSUE TITLE
Prevent keypress default actions (like scrolling)

### ISSUE THREAD

**Issue by PullJosh** [PullJosh/leopard#20]
Pretty straightforward. Arrow keys, space, etc... shouldn't perform the default action when project is focused.

Thanks to s_federici for pointing this out. :)

**Comment by micahlt** [comment]
Ah, that’s a good point... there are also those projects on Scratch use odd combinations of blocks to detect scrolling.  How are you going to handle those?

**Comment by nanaian** [comment]
I propose that scratch-js adds its own events for scrolling etc. and have the sb2-converter handle the weird block combos @micahlt describes that were used to achieve scrollbar detection.

**Comment by micahlt** [comment]
Ah, yeah!  That makes a lot of sense!
