### ISSUE TITLE
Layer Ordering: API? Implementation?

### ISSUE THREAD

**Issue by PullJosh** [PullJosh/leopard#34]
To support layer ordering, we'll need to do one of two things:
- Change `Project.sprites` from an object (which has no explicit order) to an Array, and add a `getSprite` or `sprite` method to access a sprite by name.
- Give each sprite a `layerOrder` property, and use some [complex logic like Scratch does](https://github.com/LLK/scratch-render/blob/develop/src/RenderWebGL.js#L560) to keep them in order in the renderer. Some of this logic (e.g. sorting sprites by layer order) would have to be done each frame, as we don't maintain a "draw list", instead just drawing whatever `Project.sprites` contains.

_Originally posted by @adroitwhiz in https://github.com/PullJosh/scratch-js/issues/23#issuecomment-569812205_

**Comment by PullJosh** [comment]
I don't feel like I've ever seen a good system for dealing with z-index. Ever.

Scratch's is clunky because you can't place things where you want them, only send sprites forward and backward. If you want to put sprites in a specific order, you have to run "send to back" in each sprite in order (or something similar).

CSS has the `z-index` number where you can set the value to anything and objects with higher numbers appear on top (roughly speaking).

With Scratch's relative system, it's difficult to place objects precisely. With CSS's absolute system, it's possible to put yourself in a crunch where you run out of numbers unless everything shifts around.

**Here's my proposal for a better *(?)* system:**
* `this.moveBehind()` and `this.moveAhead()` work like Scratch's go to front/back block
* `this.moveBehind(3)` and `this.moveAhead(1)` work like Scratch's move forward/backward layers block
* `this.moveBehind(this.sprites.sprite2)` places `this` behind `sprite2` but in front of everything else that was already behind `sprite2`
* `this.moveAhead(this.sprites.sprite2)` places `this` in front of `sprite2` but behind everything else that was already in front of `sprite2`

**This system is still bad because call order matters.** You can move behind or ahead of a sprite, but if that sprite moves itself later then the condition will no longer hold. This will happen frequently in practice, like if all the sprites attempt to move behind or ahead of other sprites as the first thing they do after the green flag is clicked. (In an ideal world, when you move behind or ahead of a sprite, you would automatically follow that sprite as it moves through layers in the future. That seems tricky to get right.)

---

All that was about the right API, but there's also implementation.

One concern with reordering `Project.sprites` is that it will affect the execution order of scripts. (Now that I think about it, we're currently relying on the order of `Object.values()` which isn't much better...) If we do that, we would then need a number to track the execution order of sprites, which puts us right back where we started.

**Comment by towerofnix** [comment]
>One concern with reordering Project.sprites is that it will affect the execution order of scripts. (Now that I think about it, we're currently relying on the order of Object.values() which isn't much better...) If we do that, we would then need a number to track the execution order of sprites, which puts us right back where we started.

I'm 98% sure that Scratch actually *does* base its execution order upon the looks-category layer! Check out this project to see how: https://scratch.mit.edu/projects/356670511/

**Comment by PullJosh** [comment]
@towerofnix 🤯 Wow! Great find!

It looks like the sprites on top run first, those on the bottom run later, and the stage runs last. In that case, the first option -- actually reordering the sprite list inside of `Project` -- makes sense. The only problem left is clones... How does Scratch handle them?

**Comment by towerofnix** [comment]
@PullJosh I don't have a test project on hand but I'm pretty sure clones work the same way as sprites, i.e. they're interweaved in the "execution order list" in the exact same way as in the "render list" (because those two lists are the same, just parsed in different directions). I'm pretty sure I've had to mess with that for some projects I've made :P

**Comment by PullJosh** [comment]
@towerofnix Can confirm.

https://scratch.mit.edu/projects/356672499/

**Comment by adroitwhiz** [comment]
I don't think proper layering when the flag is clicked will be as hard as it is in Scratch, because `scratch-js` lets you reach into other sprites. So you could do

```js
initializeLayers() {
  this.sprites.bottomLayer.moveAhead();
  this.sprites.oneHigher.moveAhead();
  this.sprites.middle.moveAhead();
  this.sprites.upper.moveAhead();
  this.sprites.topLayer.moveAhead();
}
```

and everything would be easily ordered properly.

**Comment by adroitwhiz** [comment]
Also note that representing sprites as an array means:
- Giving up the ezpz `this.sprites.spriteName` property access syntax (maybe in favor of `Project.sprite("spriteName")` or something similar?), or
- Replacing `Project.sprites` with a [`Proxy`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy), which AFAIK would be the first non-polyfillable ES6 feature used in this project.

**Comment by PullJosh** [comment]
@adroitwhiz That's a great point. Is it better to give each sprite a number internally to keep track of its current layer?

**Comment by towerofnix** [comment]
>Is it better to give each sprite a number internally to keep track of its current layer?

I'd refrain from this because it *could* get out of sync, potentially. Instead, a function like this would be better, IMO:

```js
getLayer() {
  return this.sprites.indexOf(this);
}
```

(Probably also `+ 1` assuming Scratch does 1-based layer indices.)

**Comment by adroitwhiz** [comment]
I think this leads into a wider question about `Project.sprites`. Currently, you can add sprites just by assigning a new property to it, and delete sprites by using the `delete` operator on one of its properties, but this doesn't give `scratch-js` any way to control what happens when you add or delete sprites.

It feels more like it was designed around an `Object` of sprites being passed once when `Project` is initialized, with no sprites being added or removed at runtime.

I think that using `Object`s for static sets and `Map`s or `Array`s for dynamic ones is more idiomatic in JS, so it comes down to whether the API should support the dynamic addition or removal of sprites in a running `Project`.

If dynamic sprite addition/removal isn't supported, the API becomes easy: just give each sprite in the object passed to the `Project` constructor a `layerOrder` property, and inside the `Project` constructor, create an `Array` of the passed sprites sorted by that property. You could also `Object.freeze` the project's `sprites` to prevent unexpected tomfoolery.

If you do want to support adding/removing sprites, I think it makes much more sense to store them as an array (as is already done for another dynamic set: sprites' clones). There would be `Project.addSprite` to add a sprite, `Project.removeSprite` to remove one, and `Project.sprite` or `Project.getSprite` to get a sprite by its name. This would mean that sprites would be accessed by their `name` property as opposed to the object key they're instantiated with, but for simplicity's sake I think that's a good thing. You could also keep the object-based `Project` constructor and automatically set a sprite's `name` based on the corresponding object key.

**Comment by PullJosh** [comment]
Is adding sprites (other than clones) while a project is running useful?

**Comment by nanaian** [comment]
> With CSS's absolute system, it's possible to put yourself in a crunch where you run out of numbers unless everything shifts around.
If we let the layer be a float - ie. a JS Number - users won't run out. You can just use decimals!

**Comment by adroitwhiz** [comment]
IMO any non-contiguous layering system is asking for trouble. Floating-point z-index in particular trades apparent simplicity for a bunch of complicated issues under the surface.

For instance, moving a sprite forward *n* layers means enumerating the first *n* sprites with a higher z-index, then swapping the *n*th sprite's z-index with the current one. Moving a sprite backwards means a similar process.

If you want to insert a new layer between two other layers, you'd have to increment the z-indices of every layer above the new layer. Note that it's not enough to make the new layer's z-index the average of the layers above and below it--if you inserted enough layers, the z-indices would be packed closer and closer and you'd quickly run out of floating-point precision.

Sprites' z-indices probably wouldn't be directly interactible anyways--that would allow too much room for annoying bugs, especially if the runtime wants to modify z-indices when, as I mentioned earlier, you perform any layering operations. If you allowed API consumers to modify z-indices, you'd open the door to them doing things like giving two layers the same z-index, or trying to move sprites forward one layer by incrementing the z-index (remember, this is a floating-point z-index so there can be an arbitrary number of sprites between successive integer z-indices!)

You'd have to sort sprites by z-index in the renderer anyway-- OpenGL's z-buffer doesn't work with transparent textures.

**Comment by PullJosh** [comment]
> @adroitwhiz: If dynamic sprite addition/removal isn't supported, the API becomes easy: just give each sprite in the object passed to the Project constructor a layerOrder property, and inside the Project constructor, create an Array of the passed sprites sorted by that property. You could also Object.freeze the project's sprites to prevent unexpected tomfoolery.

You made this comment a long time ago, and I think it's the right move. It's simple, we can implement it now without breaking anything, and it lets us reach a Scratch-compatible API quickly.

If we try to support adding/removing sprites, things get messy. (See #68) As long as clones are supported, users can always add/remove sprites that way. I'd rather get 80% of the benefit for 20% of the work.

Unless there are immediate objections, I'm going to start moving towards implementing this. I haven't dug into the renderer much yet, so this should be a good learning experience for me. 🙄

**Comment by adroitwhiz** [comment]
I don't think you'll actually have to touch any renderer code--the renderer's `_renderLayers` function takes a `Set` (unordered) of layers which should be rendered, and goes over sprites and clones in the order given in `project.spritesAndClones`.

**Comment by PullJosh** [comment]
Oh, that's great news!

**Comment by PullJosh** [comment]
Layering blocks added in 4ae101a8764751fd2d1da9b3217fe32621bfb914 🎉
