### ISSUE TITLE
Rename project for npm!

### ISSUE THREAD

**Issue by PullJosh** [PullJosh/leopard#64]
Currently, we're encouraging users to import scratch-js directly from github pages. This was fine for a while, but there isn't any version control. You're always importing the latest changes.

The best solution I can think of is to publish the package to npm and then encourage users to import using [unpkg](https://unpkg.com/). In addition to loading specific versions, this also allows us to minify & bundle everything together so it loads faster.

Unfortunately, the name [scratch-js](https://www.npmjs.com/package/scratch-js) is already taken on npm. (As is the domain [scratchjs.com](http://scratchjs.com/).) I'm planning to record a video explaining scratch-js very soon (while I have access to recording conditions), so it would be great to find a new name and publish within 24 hours.

**Anybody have name ideas?**

**Comment by shadowtime2000** [comment]
What if you tried scratch.js? Many npm packages have .js prefixes.

**Comment by PullJosh** [comment]
I'm not sure what you mean by that? It seems like there could be issues with folders that look like file names.

**Comment by shadowtime2000** [comment]
You could then rename the scratch-js folder to src.

**Comment by PullJosh** [comment]
Just checked on cat-related vocabulary, but `mew`, `purr`, `hiss`, and `paw` are all taken.

**Comment by shadowtime2000** [comment]
I think scratch.js could work. You would then have to rename the scratch-js folder to src, because it is the source folder.

**Comment by PullJosh** [comment]
cc @adroitwhiz @towerofnix Thoughts? I'm looking for a name that's available on npm and, ideally, as a .com domain. `scratch-js` just isn't going to cut it.

**Comment by PullJosh** [comment]
### Woah! `leopard` is available!
It's a big cat -- grown up Scratch. A perfect fit. And `leopardjs.dev` is an acceptable enough domain if I ever choose to buy one.

I'm honestly thrilled with this name. It's better than scratch-js ever was. Now I just have to go rename *everything*... :P

**Comment by PullJosh** [comment]
Just attempted to publish on npm and, despite being signed in, got a 403 error:

![image](https://user-images.githubusercontent.com/5458180/86048357-66850400-ba1e-11ea-8222-9f4d5573caa2.png)

My guess is that someone published a package with this name previously and then it was taken down. I'm going to contact npm to see if it's an easy fix. If not, we can publish under an organization or with a slightly modified package name.

**Comment by micahlt** [comment]
Huh, are you sure you're logged in to npm?  Love the name, btw.  If we have content, we could also get https://leopard.js.org for free.  😄

**Comment by PullJosh** [comment]
> Huh, are you sure you're logged in to npm?

Yes. Check the `npm whoami` command at the bottom of the screenshot.

> Love the name, btw.

Thanks! Me too.

> If we have content, we could also get leopard.js.org for free. 😄

Unfortunately, .js.org domains are only for Github pages websites, but we need some fancy server side-stuff to automatically translate projects.

**Comment by shadowtime2000** [comment]
@PullJosh Try [https://registry.npmjs.com](https://registry.npmjs.com/) instead.

**Comment by PullJosh** [comment]
@shadowtime2000 What do you mean by that?

**Comment by shadowtime2000** [comment]
@PullJosh Try  logging into [https://registry.npmjs.com/](https://registry.npmjs.com/) instead of [https://registry.npmjs.org](https://registry.npmjs.org). It shouldn't make a difference though, because a GET request from the browser to [https://registry.npmjs.com/leopard](https://registry.npmjs.com/leopard) shows that the package name is taken. What I do wonder is why it doesn't show up on the npm website.

**Comment by PullJosh** [comment]
@shadowtime2000 That's interesting! I'm glad that the old repo hasn't been updated since 2013, because I feel like that makes it more likely that the npm team will give away access to the repository.

**Comment by shadowtime2000** [comment]
@PullJosh They can't give access to a repository. Even if you asked the author to unpublish it so you could take it, because of how the rules of unpublished packages work, you would not have permission to publish a leopard@1.0.0, you would have to start at leopard@1.0.1, because you cannot republish a version even if the entire package is taken down by the author.

**Comment by shadowtime2000** [comment]
@PullJosh I checked and you could publish it under the name of leopard-js, because leopard, leopard.js, and leopardjs, have all been taken.

**Comment by PullJosh** [comment]
@shadowtime2000 I guess that makes sense. We could publish as `leopard-js` or `@leopardjs/leopard`.

**Comment by micahlt** [comment]
@PullJosh `@leopardjs/leopard` looks nice to me.

**Comment by shadowtime2000** [comment]
@micahlt I like the sound of `@leopardjs/leopard` too.

**Comment by PullJosh** [comment]
https://www.npmjs.com/package/@leopardjs/leopard 🎉

**Comment by PullJosh** [comment]
And now you can import javascript [directly from unpkg](https://unpkg.com/browse/@leopardjs/leopard@1.0.0/dist/)!

**Comment by PullJosh** [comment]
Interesting news: I got a response from npm and they're trying to coordinate transferring the `leopard` package to my ownership. If it works out, I'll make the switch, because I think the unprefixed name is better.

Until further updates, I'll stick with `@leopardjs/leopard`.

**Comment by PullJosh** [comment]
**Yes!** We got the name [`leopard`](https://www.npmjs.com/package/leopard)!

Shoutout to Judith from npm support for making it happen. :P
