### ISSUE TITLE
Speed comparison

### ISSUE THREAD

**Issue by sfederici** [PullJosh/leopard#75]
I have tested https://scratch.mit.edu/projects/417523534/ in Leopard. It seems a little faster in Leopard than in Scratch. But when you run it in Scratch in turbo mode, it is much faster. Is there a way to enable turbo mode in Leopard?

**Comment by PullJosh** [comment]
1. When you edit the project as Javascript, you can change the `frameRate` option in the index.js file. You should see a comment explaining what to do. 😉
2. Any time you see `yield` in the translated scripts, that's a spot where the script will pause until the next frame, when it continues. Removing `yield`s can be a nice way to get some fine-tuned control over the speed of a project. In particular, look for yields at the bottom of loops (`for` and `while`) as a great place to speed up a project. (This is essentially equivalent to setting a custom block to "run without screen refresh".)

**Comment by sfederici** [comment]
Thanks for the hints Josh. I made the changes you suggested in SandBox (fps to 60 and removed all yields at the end of loops) but the speed seems always the same. Is it necessary to "restart" the project in sandbox after you make some changes or is it just enough pressing the "greenflag" button?

**Comment by PullJosh** [comment]
Make sure you save your file! (Ctrl+S or File > Save) Once you save, your project should automatically reload with the new code. If it doesn't, let me know. :)

**Comment by sfederici** [comment]
That was exactly what I forgot :-) Now the speed is what I expected. Weird that there is no "run" button to save and reload as in other similar environments. 

`In particular, look for yields at the bottom of loops (for and while) as a great place to speed up a project. (This is essentially equivalent to setting a custom block to "run without screen refresh".)`

Of course not all yield can be removed. Is there a rule of thumb to quickly see if a yield is a needed one?

**Comment by PullJosh** [comment]
> That was exactly what I forgot :-)

Yay!

> Is there a rule of thumb to quickly see if a yield is a needed one?

If a script or function doesn't have a yield, it will try to run to completion before the screen is updated.

This means that infinite loops (like `while (true) {}`) will always need a yield. (You can't do an infinite amount of work before rendering!) On the other hand, inner loops that perform computations or move a sprite around are often great candidates for removing the `yield`. (*We want this entire computation to finish before the screen updates!*)

If you want a better peek at what's going on under the hood, it's worth exploring [generator functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function*). That's what you're writing when you include a `yield`, and it's why Leopard can pause your scripts, render to the screen, and then resume them.

**Comment by PullJosh** [comment]
A while back I recorded a video about `yield` in Leopard, but I never got around to uploading it. You've inspired me to bring the video across the finish line (thank you!), and it's now available here: https://youtu.be/t9oAZs9i7jI

Hopefully it's interesting/useful!

**Comment by sfederici** [comment]
Thanks Josh, it helped a lot. I always used Javascript at a naive level, so I didn't know about generator functions either
