### ISSUE TITLE
I'm having trouble embeding a Scratch project

### ISSUE THREAD

**Issue by MTM828** [PullJosh/leopard#87]
So... let me just explain why I'd like to use Leapord;

I was trying to display my Scratch projects on my site, so I tried embeding them using _Iframes,_ like so: `<iframe src="https://scratch.mit.edu/projects/___/embed">`. But I encountered an issue; Scratch's cookies are applying to my site and i don't wat that.
I tried the HTML _Sandbox_ attribute, but it results into Scratch "crashing". It could be because of _Ajax_ requests being blocked because of it, since it works when I set the attribute's value to  _allow-same-origin_ (thus allowing Ajax requests, but allowing cookies with it).
Then I remembered that I could use Leapord, but of course, the projects (well, 2/3 of them) fail to convert. One was super large, and the other had a hacked block.

Although this isn't entirely Leapord related, can you help? Thanks.
And I couldn't contact you via Email, Dev or Twitter since my parents won't let me. :/

**Comment by micahlt** [comment]
@MTM828 Leopard isn't currently the most stable converter out there at the moment (no offense @PullJosh).  For production usage, maybe try something like [TurboWarp](https://turbowarp.org/) until all of Leopard's bugs are fixed 😀

**Comment by MTM828** [comment]
> @MTM828 Leopard isn't currently the most stable converter out there at the moment (no offense @PullJosh). For production usage, maybe try something like [TurboWarp](https://turbowarp.org/) until all of Leopard's bugs are fixed 😀

@micahlt Yeah I'm aware of that...
Well, will TurboWarp still apply third-party cookies if I embed a project using it?
Thanks for your help, micahlt. ^^

**Comment by micahlt** [comment]
@MTM828 I'm not sure!  That might be a question for GarboMuffin (the maintainer of TurboWarp).  You could also use DevTools to check.  And no problem :)
