### ISSUE TITLE
For some reason, arrow keys not working?!

### ISSUE THREAD

**Issue by its-pablo** [PullJosh/leopard#94]
It seems like it doesn't happen with scratch, but it does with leopard. Here's the project link:
https://scratch.mit.edu/projects/524515171

Test it in scratch and in leopard. *Let me know if there's a fix!*

**Comment by its-pablo** [comment]
Wait - could it be because 
![image](https://user-images.githubusercontent.com/78528552/119047534-e687c580-b972-11eb-9732-eed418ecbe80.png)

**Comment by its-pablo** [comment]
Actually, I found it! Moving on the positive x and y axis works, 
![image](https://user-images.githubusercontent.com/78528552/119047852-4c744d00-b973-11eb-8939-eb1b90de04b8.png)
however when moving on the negative axis, it doesn't.
![image](https://user-images.githubusercontent.com/78528552/119047880-56964b80-b973-11eb-9f64-8676097f765b.png)

Please fix! :))

**Comment by its-pablo** [comment]
Fixed by taking out the starting `"" + `

**Comment by its-pablo** [comment]
Removing it didn't fix it - can anyone help?

**Comment by harry-wood** [comment]
I would guess `parseInt("-" + this.vars.speed)` would work.

**Comment by its-pablo** [comment]
Yep, figured it out
